config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant, presence: true
  has_ancestry
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comments = @restaurant.comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

    <nav class="top-bar foundation-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <a href="/"> Rielly Restaurants</a>
          </h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li>
            <%= link_to 'manage restaurants', '/admin' %>
          </li>
        </ul>
      </section>
    </nav>

    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant, restaurant_path(restaurant)%></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<div class="row">
  <h1><%= @restaurant.name %></h1>
</div>
<div class="row">
  <div class="columns medium-6">
    <p>
    <%= @restaurant.description %>
    </p>
  </div>
  <div class="columns medium-6">
    <h3>Comments</h3>
    <%= react_component('CommentList') %>
  </div>
</div>